# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci
    - run: npm run build --if-present
    
    - name: SSH Remote Commands
    # You may pin to the exact commit or the version.
    # uses: appleboy/ssh-action@334f9259f2f8eb3376d33fa4c684fff373f2c2a6
      uses: appleboy/ssh-action@v0.1.10
      with:
        host: http://45.146.166.75/
        username: root    
        key: 
        script: |
          cd ~/tg-user/
          git pull
          npm install
          pm2 delete all
          pm2 start index.js
      
    
