# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci
    - run: npm run build --if-present
    
    - name: SSH Remote Commands
    # You may pin to the exact commit or the version.
    # uses: appleboy/ssh-action@334f9259f2f8eb3376d33fa4c684fff373f2c2a6
      uses: appleboy/ssh-action@v0.1.10
      with:
        host: http://45.146.166.75/
        username: root    
        key: -----BEGIN OPENSSH PRIVATE KEY-----
b3BlbnNzaC1rZXktdjEAAAAABG5vbmUAAAAEbm9uZQAAAAAAAAABAAACFwAAAAdzc2gtcn
NhAAAAAwEAAQAAAgEAryta+cKbM5unSJzt4bKquQZfYWqQpYOc9mxng0g1RxPWgaiEdqVW
QSjMjBJnyozvY8dVjFXZYdIsSMvdsziHJYDWGBQgawW0JHDG3lEZkt7QlAiIamkViqua/M
hARCNIcQvIUYQCfnJ1mBKS9ODA2ewvrs7tyPA7hBdhDVi8ZpKq6jqZRmtH11RjPUQNb7U1
2j+wSImn5sfmhK04ja8jUVG2INXUfgblHoWChpsBwwS3jz06QL7VyBbhqtUPMuZGKcwqzk
UmTYQKOydBzhlNS/UT1wB4nIyWB1iCr6j7UebWwDGtmkoD0K/nB/Xu9gvnXrVCP4x9Ybyz
RitLhvyStqDI4MK9wjjMEaghMF+e8AZezWM0Ku10XihefWnZ7QadJguxCLwIjpTiuko7NB
+pfeDbycGHrCyGuaI4RwB9acm7kVp6ssKByBUFc+ZjOttGMrftPminL/bl0iug2bweJDNp
x+GQouQS1LaT7HSMIbMWf2dHiw9f0+3S+shuSzbCUGjd3mXugpZtEZB3FQNG5JX1KFCxEE
tYyd3DFNZ4POUMZszvnbIKSO0812NaG9q/rqVEzQbm7agSneHVPNCqdGtHH5/EHzqGJc0p
UcFjDhjqbKf97X/vBGVm6Xhf1gvKs7jE+sEiXZ4yHhvjimNEzqkPKdPGnmQutzIJLeJid+
EAAAdAlF7pypRe6coAAAAHc3NoLXJzYQAAAgEAryta+cKbM5unSJzt4bKquQZfYWqQpYOc
9mxng0g1RxPWgaiEdqVWQSjMjBJnyozvY8dVjFXZYdIsSMvdsziHJYDWGBQgawW0JHDG3l
EZkt7QlAiIamkViqua/MhARCNIcQvIUYQCfnJ1mBKS9ODA2ewvrs7tyPA7hBdhDVi8ZpKq
6jqZRmtH11RjPUQNb7U12j+wSImn5sfmhK04ja8jUVG2INXUfgblHoWChpsBwwS3jz06QL
7VyBbhqtUPMuZGKcwqzkUmTYQKOydBzhlNS/UT1wB4nIyWB1iCr6j7UebWwDGtmkoD0K/n
B/Xu9gvnXrVCP4x9YbyzRitLhvyStqDI4MK9wjjMEaghMF+e8AZezWM0Ku10XihefWnZ7Q
adJguxCLwIjpTiuko7NB+pfeDbycGHrCyGuaI4RwB9acm7kVp6ssKByBUFc+ZjOttGMrft
PminL/bl0iug2bweJDNpx+GQouQS1LaT7HSMIbMWf2dHiw9f0+3S+shuSzbCUGjd3mXugp
ZtEZB3FQNG5JX1KFCxEEtYyd3DFNZ4POUMZszvnbIKSO0812NaG9q/rqVEzQbm7agSneHV
PNCqdGtHH5/EHzqGJc0pUcFjDhjqbKf97X/vBGVm6Xhf1gvKs7jE+sEiXZ4yHhvjimNEzq
kPKdPGnmQutzIJLeJid+EAAAADAQABAAACAERivzIprPCxcFXzWhVWbLsuRzdfZJgRcUpt
GN5SZuZYUtKsqQYu1yU6Gd0HZHjZm63PCNFwRJ0hccN7v5Iz2+Mi0LJ2zQ8rG2BsnN73N2
40yaY5TJSKcOwBwdC1Fw3i3mmvyWU1jcmywsD7Y17xjaimQhlTVNaxHvMbM3sD7Q14bfxi
oyswP8xLeDDXbA1z59HMMnSnNSLuYMrkW2NJABdDuMBJ6prG81T+l24YftAVe9oSc7cKKa
jjcfeBFV1wM+0mdYGw0lrJ1TqxwUmGbDxesf+qgevQINQ+VErixDb90VIYMue8xI+I1L+x
Xji1ff7l8bagkOSCyFR5G5PX8Chx73TiQPr54V9/9w1EE9wIxOZmGPG7egpflO7yfzss7M
YFQL7Wm3tBNnVykkAh3IT6rfJIrTIkKTteGWZZ3bseX7UNJ14SimaFdyiMu6lfOoeB8obl
LvSwO9343fFiPVP1z+g3IaiPXiXe2VrmdEn5l2nyyxEHzIClJC1U0YYrwJjSGJsyEDMCY/
lvDNLVbVsZ0bSfcRBpAmYhlmf7Y5z+KmH0yoxx75+5a6xhJ121I5BG97fnHH8sR0XFMBbg
zhIZSkbE/6JHy2m1EOQxfoV2Z2hM/jgkDK3hxYnXR8e+fpTCJOlDM2bBQGRci4sZkifZ7p
knv9pq/+pkUFl1roVfAAAA/xIskNsRMk1Q5Av+9VMVW6JpgcRe5xhFhSvCiSRYCNbC+K6e
CrmNS4vXiUM4WoX12kfd1EMV/epTtvRIZMWLiFe02RMA7tlQtAycxzq0YqEsOjhVKcsHcH
ve2oGnHAzO75kDPdfBYvg9BmEp7701rGTQ3XJs3DCe3xjlGKZGo+2gNrVjgEkQnlaKARYg
jOA8i3CHTJsVGyTbnAjY+ZPTK3Jeq25sF2Qcnd23ZO0gWtQhc62f1SRU6RduNMp5MT8qTe
niJ6hMIC0d4wEL86od3NfWW03v7PAXYifTy0hDee6u0wI5XFZIHNOn4KGIVxG/2OnoL5yM
CRB/9qcilvEO6AAAAQEA0D3ue4f/tAx+AmBPbuHhZ13+oc7v94ELpnTNGe08HQAzNZb9kO
dpauNgrh03rneXpVCmgEQjTrbqIOKXmPOpad4saVKdf2bLSLbWYufANZMcNKAQ2K8iRA31
bCQvC7mniLZhedEzu/aNd7XjMOMbTHEwYZZMBioOeTfbGsIncs+A6j8GoFmcItFmRMplJ8
lGjaKD+MHVyAQMFBQFyR7z6M+us3IX46RXM50QN6DPaeS3cuySqM3MXaWHpjCgyyaJgbyJ
3Q1jutS5MtIRA6JHReJXWgXc4aNZeeuprqK6c14Uo4lDCnn+LV4zaBWxCYKFkDRr2+LkMd
McpOg0TgldewAAAQEA11e0RVw9RPvWSrYa8msPPsOpTJxg1T6FeaFNbADyIL/0NjvIJaDP
EX8XPe/Sqtne/xribpb1betuUR1eZ+mYjQWq+RtdFCdy7SOORWPayvYu/zs4KUmLw1tlDY
gzZk72eXG3sOAe7QzIOomhgedTdK9PFxeSKhadPcREbyxoT71vP4fNSL86e7kMKkxO+uGv
B8eJ7AvoArM37VlBJw6wZB4FQaxL+9AxXFZaedh6RtlM7g5WYpjCbeMCFkNjg/4RWbYMjN
WRLPBzLUSf77BthkY/EwAaZrS1NMdcdMJlQmb+5mPZ7ohgCNeprRij0vwrShFd/Eguu/PS
LjUnUzirUwAAAAtyb290QGF2ZXRpawE=
-----END OPENSSH PRIVATE KEY-----

        script: |
          cd ~/tg-user/
          git pull
          npm install
          pm2 delete all
          pm2 start index.js
      
    
